name: Deploy to GitHub Pages (gh-pages branch)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Node (optional)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: List files (debug)
        run: ls -la

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          # keep history minimal
          user_name: github-actions
          user_email: github-actions@github.com
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Prepare artifact
        run: |
          # No build step required for this plain static site. Ensure files exist.
          ls -la

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
